#!/bin/bash

git checkout .
git pull

composer install -n

php artisan migrate --force

php artisan cache:clear
php artisan config:cache
php artisan route:cache
php artisan view:cache

npm install
npm run production

supervisorctl reload
