version: '3.9'

services:

    application:
        container_name: laravel-boilerplate-application
        image: ubuntu-20.04:apache2-php8.1-composer2-node16
        build: .
        command: sh -c "
            cd /var/www
            && composer install -n
            && php artisan migrate --force
            && npm install
            && npm run production
            && ./permissions.sh
            && service cron start
            && crontab -u www-data crontab.conf
            && cp supervisor.conf /etc/supervisor/conf.d/
            && service supervisor start
            && apache2ctl -DFOREGROUND"
        depends_on:
            - database
        # Specify ports in your docker-compose.override.yml file
        # ports:
        #     - 8000:80
        volumes:
            - .:/var/www
            - node_modules:/var/www/node_modules
            - vendor:/var/www/vendor
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1GB
        restart: always

    database:
        container_name: laravel-boilerplate-database
        image: mysql:8.0.27
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: defaultdb
            MYSQL_USER: dbadmin
            MYSQL_PASSWORD: dbadmin
        # Specify ports in your docker-compose.override.yml file
        # ports:
        #     - 8001:3306
        volumes:
            - database:/var/lib/mysql
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1GB
        restart: always

    # database:
    #     container_name: laravel-boilerplate-database
    #     image: postgres:12.9
    #     environment:
    #         POSTGRES_DB: defaultdb
    #         POSTGRES_USER: dbadmin
    #         POSTGRES_PASSWORD: dbadmin
    #     # Specify ports in your docker-compose.override.yml file
    #     # ports:
    #     #     - 8001:5432
    #     volumes:
    #         - database:/var/lib/postgresql/data
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: '1.0'
    #                 memory: 1GB
    #     restart: always

volumes:
    database:
        name: laravel-boilerplate-database
    node_modules:
        name: laravel-boilerplate-node_modules
    vendor:
        name: laravel-boilerplate-vendor
