export default function lorem(count, start) {
    return [
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'Nunc eget lorem dolor sed viverra ipsum nunc.',
        'Dignissim convallis aenean et tortor.',
        'Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris.',
        'Non blandit massa enim nec.',
        'Vitae sapien pellentesque habitant morbi tristique senectus et.',
        'Integer feugiat scelerisque varius morbi enim nunc faucibus.',
        'Et ultrices neque ornare aenean euismod elementum nisi quis eleifend.',
        'Viverra mauris in aliquam sem fringilla ut morbi tincidunt.',
        'Fames ac turpis egestas sed tempus urna et pharetra.',
        'Pharetra magna ac placerat vestibulum lectus mauris.',
        'Suscipit tellus mauris a diam maecenas sed.',
        'Sit amet risus nullam eget felis eget nunc lobortis.',
        'Hac habitasse platea dictumst quisque sagittis purus sit.',
        'Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.',
        'Erat nam at lectus urna.',
        'Aliquet enim tortor at auctor.',
        'Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.',
        'Malesuada nunc vel risus commodo viverra maecenas accumsan.',
        'Iaculis at erat pellentesque adipiscing commodo elit.',
        'Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin.',
        'Fusce id velit ut tortor pretium viverra suspendisse potenti.',
        'Nec tincidunt praesent semper feugiat nibh sed pulvinar proin.',
        'Faucibus pulvinar elementum integer enim neque volutpat.',
        'Tincidunt arcu non sodales neque.',
        'Tincidunt tortor aliquam nulla facilisi cras.',
        'Malesuada fames ac turpis egestas sed tempus urna et pharetra.',
        'Proin sagittis nisl rhoncus mattis rhoncus urna.',
        'Nibh nisl condimentum id venenatis.',
        'Et malesuada fames ac turpis egestas.',
        'Ornare arcu odio ut sem.',
        'Viverra ipsum nunc aliquet bibendum enim.',
        'Orci eu lobortis elementum nibh tellus.',
        'Condimentum lacinia quis vel eros donec ac.',
        'Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus.',
        'Neque volutpat ac tincidunt vitae semper.',
        'Placerat in egestas erat imperdiet sed.',
        'Aliquam malesuada bibendum arcu vitae elementum curabitur vitae.',
        'Eu augue ut lectus arcu bibendum at varius.',
        'Pharetra et ultrices neque ornare aenean euismod.',
        'Sit amet consectetur adipiscing elit duis.',
        'Faucibus in ornare quam viverra orci sagittis eu volutpat.',
        'Pulvinar elementum integer enim neque volutpat ac.',
        'Massa sapien faucibus et molestie ac.',
        'Turpis tincidunt id aliquet risus feugiat in ante metus.',
        'Cras semper auctor neque vitae tempus quam pellentesque nec.',
        'Quam viverra orci sagittis eu volutpat odio facilisis mauris.',
        'Tincidunt arcu non sodales neque sodales ut etiam sit.',
        'Parturient montes nascetur ridiculus mus.',
        'Vitae sapien pellentesque habitant morbi tristique senectus et netus.',
        'Pharetra pharetra massa massa ultricies.',
        'Nunc sed velit dignissim sodales ut.',
        'Neque aliquam vestibulum morbi blandit cursus risus.',
        'Semper eget duis at tellus.',
        'Cursus eget nunc scelerisque viverra mauris in aliquam.',
        'Massa eget egestas purus viverra accumsan in.',
        'In nibh mauris cursus mattis molestie a iaculis at.',
        'Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar.',
        'Ut lectus arcu bibendum at varius vel.',
        'Euismod nisi porta lorem mollis aliquam ut porttitor.',
        'Amet dictum sit amet justo donec enim diam vulputate.',
        'Nibh cras pulvinar mattis nunc sed blandit libero volutpat.',
        'Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.',
        'Tortor aliquam nulla facilisi cras fermentum odio eu feugiat.',
        'Quisque egestas diam in arcu cursus euismod quis.',
        'Egestas quis ipsum suspendisse ultrices gravida dictum.',
        'Sit amet luctus venenatis lectus.',
        'Tempus egestas sed sed risus pretium quam.',
        'Porttitor rhoncus dolor purus non enim praesent elementum.',
        'Vel facilisis volutpat est velit egestas dui.',
    ]
    .slice(start ?? 0, (start ?? 0) + (count ?? 1))
    .join(' ');
};
